### ISSUE TITLE
java.lang.RuntimeException: Must unlink port before removing it.

### ISSUE THREAD

**Issue by ra4king** [ra4king/CircuitSim#47]
From error reports:

java.lang.RuntimeException: Must unlink port before removing it.
    at com.ra4king.circuitsim.simulator.CircuitState.ensureUnlinked(CircuitState.java:196)
    at com.ra4king.circuitsim.simulator.Circuit.lambda$null$3(Circuit.java:103)
    at java.lang.Iterable.forEach(Unknown Source)
    at com.ra4king.circuitsim.simulator.Circuit.lambda$updateComponent$8(Circuit.java:103)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:56)
    at com.ra4king.circuitsim.simulator.Circuit.updateComponent(Circuit.java:102)
    at com.ra4king.circuitsim.gui.CircuitBoard.lambda$updateComponent$6(CircuitBoard.java:236)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:56)
    at com.ra4king.circuitsim.gui.CircuitBoard.updateComponent(CircuitBoard.java:229)
    at com.ra4king.circuitsim.gui.CircuitSim.lambda$null$25(CircuitSim.java:959)
    at com.ra4king.circuitsim.gui.CircuitManager.mayThrow(CircuitManager.java:549)
    at com.ra4king.circuitsim.gui.CircuitSim.lambda$circuitModified$26(CircuitSim.java:956)
    at java.util.HashMap$Values.forEach(Unknown Source)
    at com.ra4king.circuitsim.gui.CircuitSim.circuitModified(CircuitSim.java:929)
    at com.ra4king.circuitsim.simulator.Circuit.lambda$null$5(Circuit.java:117)
    at java.lang.Iterable.forEach(Unknown Source)
    at com.ra4king.circuitsim.simulator.Circuit.lambda$updateComponent$8(Circuit.java:117)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:56)
    at com.ra4king.circuitsim.simulator.Circuit.updateComponent(Circuit.java:102)
    at com.ra4king.circuitsim.gui.CircuitBoard.lambda$updateComponent$6(CircuitBoard.java:236)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:56)
    at com.ra4king.circuitsim.gui.CircuitBoard.updateComponent(CircuitBoard.java:229)
    at com.ra4king.circuitsim.gui.CircuitManager.lambda$null$17(CircuitManager.java:328)
    at com.ra4king.circuitsim.gui.CircuitManager.mayThrow(CircuitManager.java:549)
    at com.ra4king.circuitsim.gui.CircuitManager.lambda$null$18(CircuitManager.java:328)
    at java.util.HashMap.forEach(Unknown Source)
    at com.ra4king.circuitsim.gui.CircuitManager.lambda$modifiedSelection$19(CircuitManager.java:326)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:56)
    at com.ra4king.circuitsim.gui.CircuitManager.modifiedSelection(CircuitManager.java:324)
    at com.ra4king.circuitsim.gui.CircuitSim.modifiedSelection(CircuitSim.java:727)
    at com.ra4king.circuitsim.gui.CircuitSim.updateProperties(CircuitSim.java:707)
    at com.ra4king.circuitsim.gui.CircuitSim.access$200(CircuitSim.java:129)
    at com.ra4king.circuitsim.gui.CircuitSim$1.lambda$null$0(CircuitSim.java:672)
    at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
    at java.lang.Thread.run(Unknown Source)

**Comment by ra4king** [comment]
Another similar report:

java.lang.RuntimeException: Must unlink port before removing it.
    at com.ra4king.circuitsim.simulator.CircuitState.ensureUnlinked(CircuitState.java:196)
    at com.ra4king.circuitsim.simulator.Circuit.lambda$null$9(Circuit.java:157)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.ra4king.circuitsim.simulator.Circuit.lambda$removeComponent$12(Circuit.java:157)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:56)
    at com.ra4king.circuitsim.simulator.Circuit.removeComponent(Circuit.java:152)
    at com.ra4king.circuitsim.gui.CircuitBoard.lambda$removeElements$23(CircuitBoard.java:696)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:56)
    at com.ra4king.circuitsim.gui.CircuitBoard.removeElements(CircuitBoard.java:680)
    at com.ra4king.circuitsim.gui.CircuitBoard.removeElements(CircuitBoard.java:676)
    at com.ra4king.circuitsim.gui.EditHistory$EditAction$5.lambda$undo$1(EditHistory.java:91)
    at com.ra4king.circuitsim.gui.CircuitManager.mayThrow(CircuitManager.java:549)
    at com.ra4king.circuitsim.gui.EditHistory$EditAction$5.undo(EditHistory.java:90)
    at com.ra4king.circuitsim.gui.EditHistory.lambda$undo$3(EditHistory.java:310)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:56)
    at com.ra4king.circuitsim.gui.EditHistory.undo(EditHistory.java:298)
    at com.ra4king.circuitsim.gui.CircuitSim.lambda$start$87(CircuitSim.java:2145)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
    at com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$1(ControlAcceleratorSupport.java:165)
    at com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(KeyboardShortcutsHandler.java:347)
    at com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(KeyboardShortcutsHandler.java:163)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
    at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
    at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
    at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
    at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
    at com.sun.glass.ui.View.notifyKey(View.java:966)

**Comment by ra4king** [comment]
I'm going to assume the fixes for issue #46 fixed this until I see a new report.

**Comment by ra4king** [comment]
It happened again with 1.9.0 :(

```
java.version=17.0.5
java.vendor=Private Build
java.vm.specification.version=17
java.vm.specification.vendor=Oracle Corporation
[java.vm.specification.name](http://java.vm.specification.name/)=Java Virtual Machine Specification
java.vm.version=17.0.5+8-Ubuntu-2ubuntu122.04
java.vm.vendor=Private Build
[java.vm.name](http://java.vm.name/)=OpenJDK 64-Bit Server VM
java.specification.version=17
java.specification.vendor=Oracle Corporation
[java.specification.name](http://java.specification.name/)=Java Platform API Specification
[os.name](http://os.name/)=Linux
os.arch=aarch64
os.version=5.15.49-linuxkit
CircuitSim version=1.9.0 2110 version


java.lang.RuntimeException: Must unlink port before removing it.
    at com.ra4king.circuitsim.simulator.CircuitState.ensureUnlinked(CircuitState.java:192)
    at com.ra4king.circuitsim.simulator.Circuit.lambda$removeComponent$9(Circuit.java:157)
    at java.base/java.lang.Iterable.forEach(Iterable.java:75)
    at com.ra4king.circuitsim.simulator.Circuit.lambda$removeComponent$12(Circuit.java:157)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:57)
    at com.ra4king.circuitsim.simulator.Circuit.removeComponent(Circuit.java:152)
    at com.ra4king.circuitsim.gui.CircuitBoard.lambda$removeElements$23(CircuitBoard.java:693)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:57)
    at com.ra4king.circuitsim.gui.CircuitBoard.removeElements(CircuitBoard.java:677)
    at com.ra4king.circuitsim.gui.CircuitBoard.removeElements(CircuitBoard.java:673)
    at com.ra4king.circuitsim.gui.CircuitManager.lambda$keyPressed$24(CircuitManager.java:663)
    at com.ra4king.circuitsim.gui.CircuitManager.mayThrow(CircuitManager.java:582)
    at com.ra4king.circuitsim.gui.CircuitManager.keyPressed(CircuitManager.java:663)
    at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    at javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4058)
    at javafx.graphics/javafx.scene.Scene$KeyHandler.access$1500(Scene.java:4004)
    at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2121)
    at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2595)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
    at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
    at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:547)
    at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:971)
    at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ra4king** [comment]
```
java.version=17.0.5
java.vendor=Private Build
java.vm.specification.version=17
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.name=Java Virtual Machine Specification
java.vm.version=17.0.5+8-Ubuntu-2ubuntu122.04
java.vm.vendor=Private Build
java.vm.name=OpenJDK 64-Bit Server VM
java.specification.version=17
java.specification.vendor=Oracle Corporation
java.specification.name=Java Platform API Specification
os.name=Linux
os.arch=amd64
os.version=5.15.79.1-microsoft-standard-WSL2
CircuitSim version=1.9.0 2110 version


java.lang.RuntimeException: Must unlink port before removing it.
    at com.ra4king.circuitsim.simulator.CircuitState.ensureUnlinked(CircuitState.java:192)
    at com.ra4king.circuitsim.simulator.Circuit.lambda$removeComponent$9(Circuit.java:157)
    at java.base/java.lang.Iterable.forEach(Iterable.java:75)
    at com.ra4king.circuitsim.simulator.Circuit.lambda$removeComponent$12(Circuit.java:157)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:57)
    at com.ra4king.circuitsim.simulator.Circuit.removeComponent(Circuit.java:152)
    at com.ra4king.circuitsim.gui.CircuitBoard.lambda$removeElements$23(CircuitBoard.java:693)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:57)
    at com.ra4king.circuitsim.gui.CircuitBoard.removeElements(CircuitBoard.java:677)
    at com.ra4king.circuitsim.gui.CircuitBoard.removeElements(CircuitBoard.java:673)
    at com.ra4king.circuitsim.gui.EditHistory$EditAction$5.lambda$undo$1(EditHistory.java:87)
    at com.ra4king.circuitsim.gui.CircuitManager.mayThrow(CircuitManager.java:582)
    at com.ra4king.circuitsim.gui.EditHistory$EditAction$5.undo(EditHistory.java:85)
    at com.ra4king.circuitsim.gui.EditHistory.lambda$undo$3(EditHistory.java:327)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:57)
    at com.ra4king.circuitsim.gui.EditHistory.undo(EditHistory.java:315)
    at com.ra4king.circuitsim.gui.CircuitSim.lambda$start$97(CircuitSim.java:2273)
    at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    at javafx.controls/javafx.scene.control.MenuItem.fire(MenuItem.java:465)
    at javafx.controls/com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$1(ControlAcceleratorSupport.java:165)
    at javafx.graphics/com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(KeyboardShortcutsHandler.java:382)
    at javafx.graphics/com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(KeyboardShortcutsHandler.java:162)
    at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    at javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4058)
    at javafx.graphics/javafx.scene.Scene$KeyHandler.access$1500(Scene.java:4004)
    at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2121)
    at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2595)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
    at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
    at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:547)
    at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:971)
```
