### ISSUE TITLE
(1.8.2) java.lang.NullPointerException: Cannot invoke "com.ra4king.circuitsim.simulator.CircuitState.getComponentProperty(com.ra4king.circuitsim.simulator.Component)" because "parentState" is null

### ISSUE THREAD

**Issue by ra4king** [ra4king/CircuitSim#76]
java.lang.NullPointerException: Cannot invoke "com.ra4king.circuitsim.simulator.CircuitState.getComponentProperty(com.ra4king.circuitsim.simulator.Component)" because "parentState" is null
    at com.ra4king.circuitsim.simulator.components.Subcircuit.getSubcircuitState(Subcircuit.java:113)
    at com.ra4king.circuitsim.gui.CircuitSim.getSubcircuitStates(CircuitSim.java:995)
    at com.ra4king.circuitsim.gui.CircuitSim.getSubcircuitStates(CircuitSim.java:1001)
    at com.ra4king.circuitsim.gui.CircuitSim.lambda$circuitModified$26(CircuitSim.java:938)
    at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
    at com.ra4king.circuitsim.gui.CircuitSim.lambda$circuitModified$27(CircuitSim.java:930)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:56)
    at com.ra4king.circuitsim.gui.CircuitSim.circuitModified(CircuitSim.java:926)
    at com.ra4king.circuitsim.gui.CircuitBoard.finalizeMove(CircuitBoard.java:616)
    at com.ra4king.circuitsim.gui.CircuitManager.mayThrow(CircuitManager.java:549)
    at com.ra4king.circuitsim.gui.CircuitManager.setSelectedElements(CircuitManager.java:237)
    at com.ra4king.circuitsim.gui.CircuitManager.mousePressed(CircuitManager.java:861)
    at com.ra4king.circuitsim.gui.CircuitSim.lambda$createCircuit$65(CircuitSim.java:1872)
    at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
    at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
    at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)
    at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
    at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
    at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
    at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ra4king** [comment]
This is a duplicate of issue #64 with a better stack trace
