### ISSUE TITLE
(1.8.2) java.lang.NullPointerException at CircuitState$LinkState.getLastPushed(CircuitState.java:249)

### ISSUE THREAD

**Issue by ra4king** [ra4king/CircuitSim#77]
java.version=1.8.0_271
java.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.specification.vendor=Oracle Corporation
[java.vm.specification.name](http://java.vm.specification.name/)=Java Virtual Machine Specification
java.vm.version=25.271-b09
java.vm.vendor=Oracle Corporation
[java.vm.name](http://java.vm.name/)=Java HotSpot(TM) 64-Bit Server VM
java.specification.version=1.8
java.specification.vendor=Oracle Corporation
[java.specification.name](http://java.specification.name/)=Java Platform API Specification
[os.name](http://os.name/)=Windows 10
os.arch=amd64
os.version=10.0
CircuitSim version=1.8.2

java.lang.NullPointerException
    at com.ra4king.circuitsim.simulator.CircuitState$LinkState.getLastPushed(CircuitState.java:249)
    at com.ra4king.circuitsim.simulator.CircuitState.getLastPushed(CircuitState.java:101)
    at com.ra4king.circuitsim.gui.peers.wiring.PinPeer.paint(PinPeer.java:174)
    at com.ra4king.circuitsim.gui.CircuitBoard.paintComponent(CircuitBoard.java:1237)
    at com.ra4king.circuitsim.gui.CircuitBoard.lambda$paint$31(CircuitBoard.java:1181)
    at java.lang.Iterable.forEach(Unknown Source)
    at com.ra4king.circuitsim.gui.CircuitBoard.paint(CircuitBoard.java:1179)
    at com.ra4king.circuitsim.gui.CircuitManager.paint(CircuitManager.java:371)
    at com.ra4king.circuitsim.gui.CircuitSim$2.handle(CircuitSim.java:2578)
    at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$0(AnimationTimer.java:57)
    at java.security.AccessController.doPrivileged(Native Method)
    at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
    at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
    at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:557)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:541)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:534)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:340)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:187)
    at java.lang.Thread.run(Unknown Source)

**Comment by ra4king** [comment]
I'm going to assume the race condition fixes in issue https://github.com/ra4king/CircuitSim/issues/46 have solved this. I'll reopen if this occurs again.
