### ISSUE TITLE
(1.8.4) java.lang.NullPointerException: Cannot invoke "com.ra4king.circuitsim.simulator.CircuitState.getComponentProperty(com.ra4king.circuitsim.simulator.Component)" because "parentState" is null

### ISSUE THREAD

**Issue by ra4king** [ra4king/CircuitSim#81]
java.version=17.0.4
java.vendor=Private Build
java.vm.specification.version=17
java.vm.specification.vendor=Oracle Corporation
[java.vm.specification.name](http://java.vm.specification.name/)=Java Virtual Machine Specification
java.vm.version=17.0.4+8-Ubuntu-120.04
java.vm.vendor=Private Build
[java.vm.name](http://java.vm.name/)=OpenJDK 64-Bit Server VM
java.specification.version=17
java.specification.vendor=Oracle Corporation
[java.specification.name](http://java.specification.name/)=Java Platform API Specification
[os.name](http://os.name/)=Linux
os.arch=amd64
os.version=5.10.124-linuxkit
CircuitSim version=1.8.4 2110 version

java.lang.NullPointerException: Cannot invoke "com.ra4king.circuitsim.simulator.CircuitState.getComponentProperty(com.ra4king.circuitsim.simulator.Component)" because "parentState" is null
    at com.ra4king.circuitsim.simulator.components.Subcircuit.getSubcircuitState(Subcircuit.java:115)
    at com.ra4king.circuitsim.gui.CircuitSim.getSubcircuitStates(CircuitSim.java:1016)
    at com.ra4king.circuitsim.gui.CircuitSim.getSubcircuitStates(CircuitSim.java:1022)
    at com.ra4king.circuitsim.gui.CircuitSim.lambda$circuitModified$26(CircuitSim.java:951)
    at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
    at com.ra4king.circuitsim.gui.CircuitSim.lambda$circuitModified$27(CircuitSim.java:940)
    at com.ra4king.circuitsim.simulator.Simulator.runSync(Simulator.java:56)
    at com.ra4king.circuitsim.gui.CircuitSim.circuitModified(CircuitSim.java:936)
    at com.ra4king.circuitsim.gui.CircuitBoard.finalizeMove(CircuitBoard.java:615)
    at com.ra4king.circuitsim.gui.CircuitManager.mayThrow(CircuitManager.java:554)
    at com.ra4king.circuitsim.gui.CircuitManager.setSelectedElements(CircuitManager.java:245)
    at com.ra4king.circuitsim.gui.CircuitSim.lambda$start$88(CircuitSim.java:2225)
    at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    at javafx.controls/javafx.scene.control.MenuItem.fire(MenuItem.java:465)
    at javafx.controls/com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$1(ControlAcceleratorSupport.java:165)
    at javafx.graphics/com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(KeyboardShortcutsHandler.java:382)
    at javafx.graphics/com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(KeyboardShortcutsHandler.java:162)
    at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    at javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4058)
    at javafx.graphics/javafx.scene.Scene$KeyHandler.access$1500(Scene.java:4004)
    at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2121)
    at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2595)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
    at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
    at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
    at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:547)
    at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:971)
    at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ra4king** [comment]
I'll close this and see if it happens again with 1.8.5+
